import {test,expect,type Page} from '@playwright/test'
import {readFile,writeFile} from 'node:fs/promises'
import {emptyTree,createNode,type MindMap} from '../../src/model.ts'
import {INDEX_KEY,docKey} from '../../src/docs.ts'
import {createPage,assignToPage,pageById} from '../../src/paper-pages.ts'
import {readPortable} from '../../src/vault-format.ts'
import {unzipSync} from 'fflate'
const id='textbox-acceptance'
function fixture():MindMap {const map=emptyTree();map.root.text='导图主题';map.rootPosition={x:450,y:300};map.floating=[{node:{...createNode('原有游离节点'),id:'leaf'},x:700,y:620}];map.objects=[{kind:'textBox',id:'box',seed:123,text:'独立文本框\n待处理事项',x:180,y:170,w:240,h:62,style:{shape:'none',fontSize:20,width:240,align:'left'}},{kind:'image',id:'image',seed:33,x:850,y:200,w:80,h:80,src:'data:image/svg+xml,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="80" height="80"><rect width="80" height="80" fill="#559966"/></svg>')},{kind:'edge',id:'edge',seed:77,from:'box',to:'leaf',label:'自由关系'}];return map}
async function start(page:Page,map=fixture()){
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(({tree,indexKey,key})=>{if(!localStorage.getItem(indexKey)){localStorage.setItem(indexKey,JSON.stringify([{id:'textbox-acceptance',createdAt:1,updatedAt:1,nameOverride:'文本框验收'}]));localStorage.setItem(key,JSON.stringify(tree));localStorage.setItem('mindnb:v2:view:textbox-acceptance',JSON.stringify({coordinateVersion:2,tx:0,ty:0,k:1,dx:0,dy:0}))}},{tree:map,indexKey:INDEX_KEY,key:docKey(id)})
 await page.goto('/#/doc/'+id);await expect(page.locator('#canvas')).toBeVisible();await page.waitForFunction(()=>!!(window as any).__mindNB);await page.evaluate(()=>document.fonts.ready);expect(errors).toEqual([]);return errors
}
async function state(page:Page):Promise<MindMap>{return page.evaluate(key=>JSON.parse(localStorage.getItem(key)!),docKey(id))}
async function point(page:Page,id:string){return page.evaluate(id=>{const d=(window as any).__mindNB,n=[...d.nodes,...d.objects].find((o:any)=>o.id===id);return{x:(n.x+n.w/2)*d.view.k+d.view.tx,y:(n.y+n.h/2)*d.view.k+d.view.ty}},id)}
async function click(page:Page,id:string,multi=false){const p=await point(page,id);if(multi)await page.keyboard.down('Meta');await page.mouse.click(p.x,p.y);if(multi)await page.keyboard.up('Meta')}
async function shortcut(page:Page,key:string){await page.locator('#canvas').focus();await page.keyboard.press(key)}
async function setting(page:Page,label:string,value:string){const input=page.getByLabel(label,{exact:true});await input.fill(value);await input.press('Tab')}

 test('A01–04/12/18/20 插入、多行编辑、身份转换、撤销重做与保存重开',async({page})=>{
 const errors=await start(page);await page.locator('#insert-menu-btn').click();await page.locator('#insert-textbox-btn').click();await page.mouse.click(180,450);const editor=page.getByLabel('文本框文字',{exact:true});await expect(editor).toBeVisible();await editor.fill('本周复盘');await editor.press('Enter');await editor.pressSequentially('下一步');await editor.press('Escape');await expect(editor).toBeHidden();const map=await state(page),created=map.objects!.find(o=>o.kind==='textBox'&&o.id!=='box')!;expect(created).toMatchObject({text:'本周复盘\n下一步',style:{shape:'none',fillPattern:'none'}});await expect(page.locator('#style-panel h2')).toHaveText('文本框');await expect(page.locator('#node-toolbar')).toBeHidden();await shortcut(page,'Tab');await shortcut(page,'Enter');expect((await state(page)).floating).toHaveLength(1)
 await page.getByLabel('所选形状',{exact:true}).selectOption('rounded');await page.getByLabel('所选填充纹理',{exact:true}).selectOption('hatchPencil');await setting(page,'所选填充颜色','#eabb55');await setting(page,'所选文本宽度','160');await page.screenshot({path:test.info().outputPath('textbox-properties.png')})
 const before=await state(page);await page.getByRole('button',{name:'转为节点',exact:true}).click();await expect(page.locator('#style-panel h2')).toHaveText('节点');expect((await state(page)).floating!.find(f=>f.node.id===created.id)?.node.text).toBe('本周复盘\n下一步');await page.locator('#toolbar-undo-btn').click();expect(await state(page)).toEqual(before);await page.locator('#toolbar-redo-btn').click();await expect(page.locator('#style-panel h2')).toHaveText('节点');await page.getByRole('button',{name:'转为文本框',exact:true}).click();await expect(page.locator('#style-panel h2')).toHaveText('文本框')
 await page.reload();await page.waitForFunction(()=>!!(window as any).__mindNB);expect((await state(page)).objects!.some(o=>o.id===created.id&&o.kind==='textBox')).toBe(true);await click(page,'box');await shortcut(page,'Delete');expect((await state(page)).objects!.some(o=>o.id==='edge')).toBe(false);await page.locator('#toolbar-undo-btn').click();expect((await state(page)).objects!.some(o=>o.id==='edge')).toBe(true);expect(errors).toEqual([])
 })
 test('A05–08/14–17 结构入口、混合选区交集与输入法保护',async({page})=>{
 const errors=await start(page);await click(page,'leaf');const more=page.locator('.node-section>.panel-group').filter({has:page.locator('summary',{hasText:'更多样式'})});await expect(more.getByText('子节点排列',{exact:true})).toHaveCount(1);await shortcut(page,'Tab');await page.getByLabel('节点文字',{exact:true}).fill('第一个子节点');await page.getByLabel('节点文字',{exact:true}).press('Escape');await click(page,'leaf');await expect(page.locator('.node-section > details').filter({has:page.locator(':scope > summary',{hasText:'子节点排列'})})).toHaveCount(1);await shortcut(page,'-');await expect(page.locator('.node-section > details').filter({has:page.locator(':scope > summary',{hasText:'子节点排列'})})).toHaveCount(1);await expect(page.getByRole('button',{name:'转为文本框',exact:true})).toBeDisabled();await shortcut(page,'-')
 const child=(await state(page)).floating![0].node.children[0].id;await click(page,child);await shortcut(page,'Delete');await click(page,'leaf');await expect(more.getByText('子节点排列',{exact:true})).toHaveCount(1)
 await click(page,'box');await click(page,'leaf',true);await expect(page.locator('#style-panel h2')).toHaveText('文本框 + 节点（2）');await expect(page.getByLabel('所选字号',{exact:true})).toHaveAttribute('placeholder','混合');const before=await state(page);await setting(page,'所选字号','32');const after=await state(page);expect(after.floating![0].node.style?.fontSize).toBe(32);expect(after.objects!.find(o=>o.id==='box')).toMatchObject({style:{fontSize:32}});await shortcut(page,'Tab');expect((await state(page)).floating![0].node.children).toHaveLength(0);await page.locator('#toolbar-undo-btn').click();expect(await state(page)).toEqual(before);await page.screenshot({path:test.info().outputPath('mixed-properties.png')})
 await click(page,'image',true);await expect(page.getByLabel('所选字号',{exact:true})).toBeHidden();await expect(page.locator('#node-toolbar')).toBeHidden();await shortcut(page,'Tab');expect((await state(page)).floating![0].node.children).toHaveLength(0)
 await click(page,'box');await shortcut(page,'F2');const editor=page.getByLabel('文本框文字',{exact:true});await editor.dispatchEvent('compositionstart');await editor.dispatchEvent('keydown',{key:'Enter',isComposing:true});await expect(editor).toBeVisible();await editor.dispatchEvent('compositionend');await editor.fill('中文输入法确认后');await editor.press('Escape');expect((await state(page)).objects!.find(o=>o.id==='box')).toMatchObject({text:'中文输入法确认后'});expect(errors).toEqual([])
 })
 test('A10/11/19/21/23 关系线跟随、深色纸页、视觉输出与可携带文档',async({page})=>{
 let map=fixture();map.rootPosition={x:670,y:420};map.objects=map.objects!.filter(o=>o.kind!=='image');const made=createPage(map,{x:80,y:100,preset:'custom'});map=assignToPage(made.map,made.id,['box','leaf',map.root.id]);Object.assign(pageById(map,made.id)!,{paper:'#18251e',w:940,h:800});const errors=await start(page,map);await click(page,'box');const p=await point(page,'box');await page.mouse.move(p.x,p.y);await page.mouse.down();await page.mouse.move(p.x+100,p.y+50,{steps:10});await page.mouse.up();await setting(page,'所选文本宽度','150');expect((await state(page)).pages![0].members).toContain('box');expect((await state(page)).objects!.find(o=>o.id==='edge')).toMatchObject({from:'box',to:'leaf'});await page.getByRole('button',{name:'复制文本框',exact:true}).click();expect((await state(page)).objects!.filter(o=>o.kind==='edge')).toHaveLength(1);const copy=(await state(page)).objects!.find(o=>o.kind==='textBox'&&o.id!=='box')!;const cp=await point(page,copy.id);await page.mouse.move(cp.x,cp.y);await page.mouse.down();await page.mouse.move(cp.x+240,cp.y-24,{steps:10});await page.mouse.up()
 await page.locator('#export-png-btn').click();const d=page.getByRole('dialog',{name:'导出文档',exact:true});await expect(d).toContainText('不包含独立文本框');await d.getByLabel('导出格式').selectOption('mindnb');let pending=page.waitForEvent('download');await d.getByRole('button',{name:'导出',exact:true}).click();let download=await pending;const portable=(await readPortable(new Uint8Array(await readFile((await download.path())!)))).tree;expect(portable.objects!.filter(o=>o.kind==='textBox')).toHaveLength(2)
 for(const format of ['png','jpeg','svg','pdf','md','docx','xlsx','opml','textbundle']){await d.getByLabel('导出格式').selectOption(format);pending=page.waitForEvent('download');await d.getByRole('button',{name:'导出',exact:true}).click();download=await pending;const bytes=await readFile((await download.path())!);expect(bytes.length,format).toBeGreaterThan(format==='md'?0:100);await writeFile(test.info().outputPath('whole.'+format),bytes);if(format==='svg'){expect(bytes.toString()).toContain('data-textbox-id');expect(bytes.toString()).toContain('独立文本框')}if(format==='md'||format==='opml'){expect(bytes.toString()).not.toContain('独立文本框');expect(bytes.toString()).toContain('导图主题')}if(['docx','xlsx','textbundle'].includes(format)){const contents=Object.values(unzipSync(bytes)).map(b=>Buffer.from(b).toString()).join('');expect(contents).not.toContain('独立文本框');expect(contents).toContain('导图主题')}}
 await d.getByRole('button',{name:'按页导出图片 / PDF…',exact:true}).click();const pages=page.getByRole('dialog',{name:'按页导出',exact:true});await pages.getByLabel('导出图片宽度').fill('700');await pages.getByLabel('导出图片宽度').press('Tab');await expect(pages.getByRole('button',{name:'导出',exact:true})).toBeEnabled();await expect(pages.locator('img')).toHaveCount(1);await page.screenshot({path:test.info().outputPath('dark-page-export.png')});pending=page.waitForEvent('download');await pages.getByRole('button',{name:'导出',exact:true}).click();download=await pending;const output=await readFile((await download.path())!);const png=download.suggestedFilename().endsWith('.zip')?Object.values(unzipSync(output))[0]:output;await writeFile(test.info().outputPath('page.png'),png);expect(Buffer.from(png).readUInt32BE(16)).toBe(700);for(const format of ['jpg','pdf']){await pages.getByLabel('纸页导出格式').selectOption(format);await expect(pages.getByRole('button',{name:'导出',exact:true})).toBeEnabled();pending=page.waitForEvent('download');await pages.getByRole('button',{name:'导出',exact:true}).click();download=await pending;const bytes=await readFile((await download.path())!);expect(bytes.length).toBeGreaterThan(1000);await writeFile(test.info().outputPath('page.'+format),bytes)}await pages.getByRole('button',{name:'关闭',exact:true}).click();await page.locator('#toolbar-home-btn').click();await expect(page.locator('.card-thumb [data-textbox-id]')).toHaveCount(2);expect(errors).toEqual([])
 })
 test('A04–08/12/13 原有游离节点快捷键、排列预设和外观保真',async({page})=>{
 const errors=await start(page);await page.mouse.dblclick(180,480);await expect(page.getByLabel('节点文字',{exact:true})).toBeVisible();await page.getByLabel('节点文字',{exact:true}).fill('独立的节点');await page.getByLabel('节点文字',{exact:true}).press('Escape');let map=await state(page);const made=map.floating!.find(f=>f.node.id!=='leaf')!.node.id
 await page.locator('.node-section > details > summary').filter({hasText:'更多样式'}).click();await page.locator('.node-section details > summary').filter({hasText:'子节点排列'}).click();await page.getByRole('button',{name:'子节点排列',exact:true}).click();await page.getByRole('dialog',{name:'子节点排列选项',exact:true}).getByRole('button',{name:'组织结构图·向下',exact:true}).click();expect((await state(page)).floating!.find(f=>f.node.id===made)!.node.structure).toBe('orgDown')
 await click(page,made);await shortcut(page,'Tab');await page.getByLabel('节点文字',{exact:true}).fill('按预设生长');await page.getByLabel('节点文字',{exact:true}).press('Escape');map=await state(page);const child=map.floating!.find(f=>f.node.id===made)!.node.children[0].id;await click(page,made);await expect(page.locator('.node-section > details > summary').filter({hasText:'子节点排列'})).toBeVisible();await click(page,child);await expect(page.locator('.node-section > details > summary').filter({hasText:'分支线样式'})).toBeVisible();await shortcut(page,'Delete');await click(page,made);expect((await state(page)).floating!.find(f=>f.node.id===made)!.node.structure).toBe('orgDown');await expect(page.getByRole('button',{name:'转为文本框',exact:true})).toBeDisabled();await expect(page.locator('.text-identity-actions')).toContainText('结构预设')
 await click(page,'leaf');const typography=async(selector:string)=>page.locator(selector).locator('text').evaluateAll(els=>els.map(e=>({text:e.textContent,font:e.getAttribute('font-size'),weight:e.getAttribute('font-weight'),fill:e.getAttribute('fill'),x:e.getAttribute('x'),y:e.getAttribute('y')})))
 const before=await typography('#canvas [data-id="leaf"]');await page.getByRole('button',{name:'转为文本框',exact:true}).click();expect(await typography('#canvas [data-textbox-id="leaf"]')).toEqual(before)
 await click(page,'box');const edgeBefore=await page.locator('[data-edge-id="edge"]').getAttribute('stroke');await page.getByRole('button',{name:'转为节点',exact:true}).click();await expect(page.locator('[data-edge-id="edge"]')).toHaveAttribute('stroke',edgeBefore!);await page.locator('#toolbar-undo-btn').click();await expect(page.locator('[data-edge-id="edge"]')).toHaveAttribute('stroke',edgeBefore!);expect(errors).toEqual([])
 })
